#!/bin/bash

set -ex
cd $(dirname $0)/..

triplet=$1
if [[ $triplet =~ x86-.* ]]; then
    wordsize=32
else
    wordsize=64
fi

if [[ $triplet =~ .*-mingw-.* ]]; then
    pacman -Sy --noconfirm make base-devel tar zip unzip
    if [ ! -x /c/msys64/mingw$wordsize/bin/g++.exe ]; then
        if [[ $wordsize == 64 ]]; then
            pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
        else
            pacman -Sy --noconfirm mingw-w64-i686-toolchain
        fi
    fi
    g++ -v
else
    # Don't use the vcpkg that ships with msvc
    unset VCPKG_ROOT
    cl
fi
PATH=/c/msys64/mingw$wordsize/bin:$PATH

cwd=`pwd`
rm -rf stage/$triplet
mkdir -p stage

git clone --depth 1 https://github.com/microsoft/vcpkg
./vcpkg/bootstrap-vcpkg.sh
./vcpkg/vcpkg install zlib openssl libjpeg-turbo --triplet $triplet
./vcpkg/vcpkg list
mv ./vcpkg/installed/$triplet stage/
./vcpkg/vcpkg list > stage/$triplet/vcpkg-list
